#!/bin/sh
# http://ctags.sourceforge.net/ctags.html for info about the ctags commands 
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "\$dir/\$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative=yes -L - -f"$dir/$$.tags" 
mv "$dir/$$.tags" "$dir/tags"

