[mgr]
ratio = [0, 1, 0]
show_hidden = true

[opener]
edit = [
  { run = 'zellij run --floating --close-on-exit -- nvim "$@"', block = false, desc = "nvim (float)" },
  { run = 'nvim "$@"', block = true, desc = "nvim" },
]
